#ifndef PW_BOARD_RESOURCES_H
#define PW_BOARD_RESOURCES_H

#define COMMON_SPI_SCK_PIN 2
#define COMMON_SPI_MOSI_PIN 3
#define COMMON_SPI_MISO_PIN 4
#define COMMON_SPI_HW spi0
#define COMMON_SPI_SPEED_HZ 10000000 // 10 MHz

#define COMMON_I2C_SCK_PIN 21
#define COMMON_I2C_SDA_PIN 20
#define COMMON_I2C_HW i2c0
#define COMMON_I2C_SPEED_HZ 100000 // 100 kHz

#define COMMON_SYSCLK_HZ 150000000 // 150 MHz

#define ACCEL_SCK_PIN COMMON_SPI_SCK_PIN
#define ACCEL_MOSI_PIN COMMON_SPI_MOSI_PIN
#define ACCEL_MISO_PIN COMMON_SPI_MISO_PIN
#define ACCEL_SPI_HW COMMON_SPI_HW
#define ACCEL_CSB_PIN 7
#define ACCEL_INT_PIN 8

#define AUDIO_SPEAKER_PIN 2
#define AUDIO_ALARM_NUM 1

#define BAT_I2C_SCK_PIN COMMON_I2C_SCK_PIN
#define BAT_I2C_SDA_PIN COMMON_I2C_SDA_PIN
#define BAT_I2C_HW COMMON_I2C_HW
#define BAT_I2C_SPEED_HZ COMMON_I2C_SPEED_HZ
#define BAT_INT_PIN 27
#define BAT_CE_PIN 28
#define BAT_I2C_ADDR 0x6a

#define BUTTON_LEFT_PIN 26
#define BUTTON_MIDDLE_PIN 22
#define BUTTON_RIGHT_PIN 19

#define EEPROM_SCK_PIN COMMON_SPI_SCK_PIN
#define EEPROM_MOSI_PIN COMMON_SPI_MOSI_PIN
#define EEPROM_MISO_PIN COMMON_SPI_MISO_PIN
#define EEPROM_SPI_HW COMMON_SPI_HW
#define EEPROM_CSB_PIN 6

#define IR_TX_PIN 11
#define IR_RX_PIN 10
#define IR_SD_PIN 9
#define IR_PIO_HW pio1
#define IR_PIO_SM 0
#define IR_DMA_CHAN 0
#define IR_DMA_IRQ_NUM 0

#define USER_IDLE_ALARM_NUM 0

#define SCREEN_SCK_PIN 13
#define SCREEN_SD0_PIN 15
#define SCREEN_SD1_PIN 14
#define SCREEN_SD2_PIN 17
#define SCREEN_SD3_PIN 16
#define SCREEN_PIO_SD_START_PIN SCREEN_SD3_PIN
#define SCREEN_CSB_PIN 18
#define SCREEN_RST_PIN 12
#define SCREEN_PWREN_PIN 0xff

#define SCREEN_PIO_HW pio0
#define SCREEN_PIO_SM 0

void board_spi_init();
void board_i2c_init();

#endif /* PW_BOARD_RESOURCES_H */
