#ifndef BATTERY_PICO_B25628E_H
#define BATTERY_PICO_B25628E_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

<<<<<<< HEAD:src/drivers/battery/battery_pico_bq25628e.h
<<<<<<< HEAD
#define BAT_INT_PIN 3
#define BAT_CE_PIN  4

#define PMIC_I2C_SCL_PIN 1
#define PMIC_I2C_SDA_PIN 0
=======
#define BAT_INT_PIN 27  // GP27, phys 32
#define BAT_CE_PIN  28  // GP28, phys 34

#define PMIC_I2C_SCL_PIN 21  // GP21, phys 27
#define PMIC_I2C_SDA_PIN 20  // GP20, phys 26
>>>>>>> 97250e6 (RP2350TouchLCD128 Working)

#define PMIC_I2C_SPEED_KHZ 100 // Supports 400 and 1000 also but needs more timing requirements
#define PMIC_I2C_ADDRESS 0x6a

#define PMIC_I2C i2c0
=======
#define ADC_TIMEOUT_MS 100
>>>>>>> 5cad753 (rebase survival):src/drivers/battery/bq25628e_rp2xxx_i2c.h

<<<<<<< HEAD
#define ADC_TIMEOUT_MS 100

=======
>>>>>>> 97250e6 (RP2350TouchLCD128 Working)
/*
 * Taken from datasheet https://www.ti.com/lit/ds/symlink/bq25628e.pdf
 * For limits and ADC values, see associated table for range, step, etc.
 */
enum bq25628e_reg_address_e {
    REG_CHARGE_CURRENT_LIMIT = 0x02,    // Table 8-7
    REG_CHARGE_VOLTAGE_LIMIT = 0x04,    // Table 8-8
    REG_INPUT_CURRENT_LIMIT = 0x06,     // Table 8-9
    REG_INPUT_VOLTAGE_LIMIT = 0x08,     // Table 8-10
    REG_MINIMAL_SYSTEM_VOLTAGE = 0x0e,  // Table 8-11
    REG_PRE_CHARGE_CONTROL = 0x10,      // Table 8-12
    REG_TERMINATION_CONTROL = 0x12,     // Table 8-13
    REG_CHARGE_CONTROL = 0x14,
    REG_CHARGE_TIMER_CONTROL = 0x15,
    REG_CHARGER_CONTROL_0 = 0x16,
    REG_CHARGER_CONTROL_1 = 0x17,
    REG_CHARGER_CONTROL_2 = 0x18,
    REG_CHARGER_CONTROL_3 = 0x19,
    REG_NTC_CONTROL_0 = 0x1a,
    REG_NTC_CONTROL_1 = 0x1b,
    REG_NTC_CONTROL_2 = 0x1c,
    REG_CHARGER_STATUS_0 = 0x1d,
    REG_CHARGER_STATUS_1 = 0x1e,
    REG_FAULT_STATUS_0 = 0x1F,
    REG_CHARGER_FLAG_0 = 0x20,
    REG_CHARGER_FLAG_1 = 0x21,
    REG_FAULT_FLAG_0 = 0x22,
    REG_CHARGER_MASK_0 = 0x20,
    REG_CHARGER_MASK_1 = 0x21,
    REG_FAULT_MASK_0 = 0x22,
    REG_ADC_CONTROL = 0x26,
    REG_ADC_FUNCTION_DISABLE_0 = 0x27,
    REG_IBUS_ADC = 0x28,    // Table 8-34
    REG_IBAT_ADC = 0x2a,    // Table 8-35
    REG_VBUS_ADC = 0x2c,    // Table 8-36
    REG_VPMID_ADC = 0x2e,   // Table 8-37
    REG_VBAT_ADC = 0x30,    // Table 8-38
    REG_VSYS_ADC = 0x32,    // Table 8-39
    REG_TS_ADC = 0x34,      // Table 8-40
    REG_TDIE_ADC = 0x36,    // Table 8-41
    REG_PART_INFO = 0x38,   // Table 8-42
};

#define REG_CHARGE_CURRENT_LIMIT_ICHG(x) (((x)&0x3f)<<5)
#define REG_CHARGE_VOLTAGE_LIMIT_VREG(x) (((x)&0x1ff)<<3)
#define REG_INPUT_CURRENT_LIMIT_REG_IINDPM(x) (((x)&0xff)<<4)
#define REG_INPUT_VOLTAGE_LIMIT_REG_VINDPM(x) (((x)&0x1ff)<<5)
#define REG_MINIMAL_SYSTEM_VOLTAGE_VSYSMIN(x) (((x)&0x3f)<<6)
#define REG_PRE_CHARGE_CONTROL_IPRECHG(x) (((x)&0x1f)<<3)
#define REG_TERMINATION_CONTROL_ITERM(x) (((x)&0x3f)<<2)
#define REG_CHARGE_CONTROL_VRECHG_MSK       (1<<0)
#define REG_CHARGE_CONTROL_VRECHG_100MV     (0<<0)
#define REG_CHARGE_CONTROL_VRECHG_200MV     (1<<0)
#define REG_CHARGE_CONTROL_VINDPM_BAT_TRACK_MSK         (1<<1)
#define REG_CHARGE_CONTROL_VINDPM_BAT_TRACK_DISABLE     (0<<1)
#define REG_CHARGE_CONTROL_VINDPM_BAT_TRACK_VBAT_400MV  (1<<1)
#define REG_CHARGE_CONTROL_EN_TERM_MSK      (1<<2)
#define REG_CHARGE_CONTROL_EN_TERM_DISABLED (0<<2)
#define REG_CHARGE_CONTROL_EN_TERM_ENABLED  (1<<2)
#define REG_CHARGE_CONTROL_TOPOFF_TMR_MSK       (0b11<<3)
#define REG_CHARGE_CONTROL_TOPOFF_TMR_DISABLED  (0b00<<3)
#define REG_CHARGE_CONTROL_TOPOFF_TMR_17MINS    (0b01<<3)
#define REG_CHARGE_CONTROL_TOPOFF_TMR_35MINS    (0b10<<3)
#define REG_CHARGE_CONTROL_TOPOFF_TMR_52MINS    (0b11<<3)
#define REG_CHARGE_CONTROL_ITRICKLE_MSK     (1<<5)
#define REG_CHARGE_CONTROL_ITRICKLE_10MA    (0<<5)
#define REG_CHARGE_CONTROL_ITRICKLE_40MA    (1<<5)
#define REG_CHARGE_CONTROL_Q4_FULLON_MSK        (1<<6)
#define REG_CHARGE_CONTROL_Q4_FULLON_VARIABLE   (1<<6)
#define REG_CHARGE_CONTROL_Q4_FULLON_CONSTANT   (1<<6)
#define REG_CHARGE_CONTROL_Q1_FULLON_MSK        (1<<7)
#define REG_CHARGE_CONTROL_Q1_FULLON_VARIABLE   (0<<7)
#define REG_CHARGE_CONTROL_Q1_FULLON_CONSTANT   (1<<7)
#define REG_CHARGE_TIMER_CONTROL_CHG_TMR_MSK        (1<<0)
#define REG_CHARGE_TIMER_CONTROL_CHG_TMR_14_5HRS    (0<<0)
#define REG_CHARGE_TIMER_CONTROL_CHG_TMR_18_HRS     (1<<0)
#define REG_CHARGE_TIMER_CONTROL_PRECHG_TMR_MSK         (1<<1)
#define REG_CHARGE_TIMER_CONTROL_PRECHG_TMR_2_5HRS      (0<<1)
#define REG_CHARGE_TIMER_CONTROL_PRECHG_TMR_0_62HRS     (1<<1)
#define REG_CHARGE_TIMER_CONTROL_EN_SAFETY_TMRS_MSK         (1<<2)
#define REG_CHARGE_TIMER_CONTROL_EN_SAFETY_TMRS_DISABLED    (0<<2)
#define REG_CHARGE_TIMER_CONTROL_EN_SAFETY_TMRS_ENABLED     (1<<2)
#define REG_CHARGE_TIMER_CONTROL_TMR_2X_EN_MSK      (1<<3)
#define REG_CHARGE_TIMER_CONTROL_TMR_2X_EN_DISABLED (0<<3) // NOT slowed by 2x
#define REG_CHARGE_TIMER_CONTROL_TMR_2X_EN_ENABLED  (1<<3) // IS slowed by 2x
#define REG_CHARGE_TIMER_CONTROL_DIS_STAT_MSK       (1<<7)
#define REG_CHARGE_TIMER_CONTROL_DIS_STAT_ENABLED   (0<<7) // STAT pin enabled
#define REG_CHARGE_TIMER_CONTROL_DIS_STAT_DISABLED  (1<<7) // STAT pin disabeld
#define REG_CHARGER_CONTROL_0_WATCHDOG_MSK      (0b11<<0)
#define REG_CHARGER_CONTROL_0_WATCHDOG_DISABLED (0b00<<0)
#define REG_CHARGER_CONTROL_0_WATCHDOG_50SEC    (0b01<<0)
#define REG_CHARGER_CONTROL_0_WATCHDOG_100SEC   (0b10<<0)
#define REG_CHARGER_CONTROL_0_WATCHDOG_200SEC   (0b11<<0)
#define REG_CHARGER_CONTROL_0_WD_RST_MSK    (1<<2)
#define REG_CHARGER_CONTROL_0_WD_RST        (1<<2)
#define REG_CHARGER_CONTROL_0_FORCE_PMID_DIS_MSK        (1<<3)
#define REG_CHARGER_CONTROL_0_FORCE_PMID_DIS_DISABLED   (0<<3)
#define REG_CHARGER_CONTROL_0_FORCE_PMID_DIS_ENABLED    (1<<3)
#define REG_CHARGER_CONTROL_0_EN_HIZ_MSK        (1<<4)
#define REG_CHARGER_CONTROL_0_EN_HIZ_DISABLED   (0<<4)
#define REG_CHARGER_CONTROL_0_EN_HIZ_ENABLED    (1<<4)
#define REG_CHARGER_CONTROL_0_EN_CHG_MSK        (1<<5)
#define REG_CHARGER_CONTROL_0_EN_CHG_DISABLED   (0<<5)
#define REG_CHARGER_CONTROL_0_EN_CHG_ENABLED    (1<<5)
#define REG_CHARGER_CONTROL_0_FORCE_IBATDIS_MSK         (1<<6)
#define REG_CHARGER_CONTROL_0_FORCE_IBATDIS_DISABLED    (0<<6)
#define REG_CHARGER_CONTROL_0_FORCE_IBATDIS_ENABLED     (1<<6)
#define REG_CHARGER_CONTROL_0_EN_AUTO_IBATDIS_MSK       (1<<7)
#define REG_CHARGER_CONTROL_0_EN_AUTO_IBATDIS_DISABLED  (1<<7) // DENY current when OVP triggered
#define REG_CHARGER_CONTROL_0_EN_AUTO_IBATDIS_ENABLED   (1<<7) // ALLOW current when OVP triggered
#define REG_CHARGER_CONTROL_1_VBUS_OVP_MSK  (1<<0)
#define REG_CHARGER_CONTROL_1_VBUS_OVP_6V3  (0<<0)
#define REG_CHARGER_CONTROL_1_VBUS_OVP_16V5 (1<<0)
#define REG_CHARGER_CONTROL_1_SET_CONV_STRN_MSK         (0b11<<2)
#define REG_CHARGER_CONTROL_1_SET_CONV_STRN_WEAK        (0b00<<2)
#define REG_CHARGER_CONTROL_1_SET_CONV_STRN_NORMAL      (0b01<<2)
#define REG_CHARGER_CONTROL_1_SET_CONV_STRN_RESERVED    (0b10<<2)
#define REG_CHARGER_CONTROL_1_SET_CONV_STRN_STRONG      (0b11<<2)
#define REG_CHARGER_CONTROL_1_SET_CONV_FREQ_MSK         (0b11<<4)
#define REG_CHARGER_CONTROL_1_SET_CONV_FREQ_1_50MHZ     (0b00<<4)
#define REG_CHARGER_CONTROL_1_SET_CONV_FREQ_1_35MHZ     (0b01<<4)
#define REG_CHARGER_CONTROL_1_SET_CONV_FREQ_1_65MHZ     (0b10<<4)
#define REG_CHARGER_CONTROL_1_SET_CONV_FREQ_RESERVED    (0b11<<4)
#define REG_CHARGER_CONTROL_1_TREG_MSK  (1<<6)
#define REG_CHARGER_CONTROL_1_TREG_60C  (0<<6)
#define REG_CHARGER_CONTROL_1_TREG_120C (1<<6)
#define REG_CHARGER_CONTROL_1_REG_RST_MSK   (1<<7)
#define REG_CHARGER_CONTROL_1_REG_RST       (1<<7)  // Perform reset
#define REG_CHARGER_CONTROL_2_BATFET_CTRL_MSK           (0b11<<0)
#define REG_CHARGER_CONTROL_2_BATFET_CTRL_NORMAL        (0b00<<0)
#define REG_CHARGER_CONTROL_2_BATFET_CTRL_SHUTDOWN      (0b01<<0)
#define REG_CHARGER_CONTROL_2_BATFET_CTRL_SHIP          (0b10<<0)
#define REG_CHARGER_CONTROL_2_BATFET_CTRL_SYS_PWR_RST   (0b11<<0)
#define REG_CHARGER_CONTROL_2_BATFET_DLY_MSK    (1<<2)
#define REG_CHARGER_CONTROL_2_BATFET_DLY_20MS   (0<<2)
#define REG_CHARGER_CONTROL_2_BATFET_DLY_10S    (1<<2)
#define REG_CHARGER_CONTROL_2_BATFET_CTRL_WVBUS_MSK (1<<3)
#define REG_CHARGER_CONTROL_2_BATFET_CTRL_WVBUS     (1<<3)
#define REG_CHARGER_CONTROL_2_BATFET_CTRL_PFM_FWD_MSK       (1<<4)
#define REG_CHARGER_CONTROL_2_BATFET_CTRL_PFM_FWD_ENABLE    (0<<4)
#define REG_CHARGER_CONTROL_2_BATFET_CTRL_PFM_FWD_DISABLE   (1<<4)
#define REG_CHARGER_CONTROL_3_CHG_RATE_MSK  (0b11<<0)
#define REG_CHARGER_CONTROL_3_CHG_RATE_1C   (0b00<<0)
#define REG_CHARGER_CONTROL_3_CHG_RATE_2C   (0b01<<0)
#define REG_CHARGER_CONTROL_3_CHG_RATE_4C   (0b10<<0)
#define REG_CHARGER_CONTROL_3_CHG_RATE_6C   (0b11<<0)
#define REG_CHARGER_CONTROL_3_EN_EXTILIM_MSK        (1<<2)
#define REG_CHARGER_CONTROL_3_EN_EXTILIM_DISABLED   (0<<2)
#define REG_CHARGER_CONTROL_3_EN_EXTILIM_ENABLED    (1<<2)
#define REG_CHARGER_CONTROL_3_VBAT_UVLO_MSK (1<<5)
#define REG_CHARGER_CONTROL_3_VBAT_UVLO_2V2 (0<<5)
#define REG_CHARGER_CONTROL_3_VBAT_UVLO_1V8 (1<<5)
#define REG_CHARGER_CONTROL_3_IBAT_PK_MSK   (0b11<<6)
#define REG_CHARGER_CONTROL_3_IBAT_PK_1_5A  (0b00<<6)
#define REG_CHARGER_CONTROL_3_IBAT_PK_3A    (0b01<<6)
#define REG_CHARGER_CONTROL_3_IBAT_PK_6A    (0b10<<6)
#define REG_CHARGER_CONTROL_3_IBAT_PK_12A   (0b11<<6)
#define REG_NTC_CONTROL_0_TS_ISET_COOL_MSK          (0b11<<0)
#define REG_NTC_CONTROL_0_TS_ISET_COOL_SUSP         (0b00<<0)
#define REG_NTC_CONTROL_0_TS_ISET_COOL_20PCT        (0b01<<0)
#define REG_NTC_CONTROL_0_TS_ISET_COOL_40PCT        (0b10<<0)
#define REG_NTC_CONTROL_0_TS_ISET_COOL_UNCHANGED    (0b11<<0)
#define REG_NTC_CONTROL_0_TS_ISET_WARM_MSK          (0b11<<2)
#define REG_NTC_CONTROL_0_TS_ISET_WARM_SUSP         (0b00<<2)
#define REG_NTC_CONTROL_0_TS_ISET_WARM_20PCT        (0b01<<2)
#define REG_NTC_CONTROL_0_TS_ISET_WARM_40PCT        (0b10<<2)
#define REG_NTC_CONTROL_0_TS_ISET_WARM_UNCHANGED    (0b11<<2)
#define REG_NTC_CONTROL_0_TS_IGNORE_MSK     (1<<7)
#define REG_NTC_CONTROL_0_TS_IGNORE         (1<<7)
#define REG_NTC_CONTROL_0_TS_NO_IGNORE      (0<<7)
#define REG_NTC_CONTROL_1_TS_VSET_WARM_MSK          (0b11<<0)
#define REG_NTC_CONTROL_1_TS_VSET_WARM_300MV        (0b00<<0)
#define REG_NTC_CONTROL_1_TS_VSET_WARM_200MV        (0b01<<0)
#define REG_NTC_CONTROL_1_TS_VSET_WARM_100MV        (0b10<<0)
#define REG_NTC_CONTROL_1_TS_VSET_WARM_UNCHANGED    (0b11<<0)
#define REG_NTC_CONTROL_1_TS_TH456(x)   (((x)&0x07)<<2)
#define REG_NTC_CONTROL_1_TS_TH123(x)   (((x)&0x07)<<5)
#define REG_NTC_CONTROL_2_TS_ISET_PRECOOL_MSK           (0b11<<0)
#define REG_NTC_CONTROL_2_TS_ISET_PRECOOL_SUSP          (0b00<<0)
#define REG_NTC_CONTROL_2_TS_ISET_PRECOOL_20PCT         (0b01<<0)
#define REG_NTC_CONTROL_2_TS_ISET_PRECOOL_40PCT         (0b10<<0)
#define REG_NTC_CONTROL_2_TS_ISET_PRECOOL_UNCHANGED     (0b11<<0)
#define REG_NTC_CONTROL_2_TS_ISET_PREWARM_MSK           (0b11<<2)
#define REG_NTC_CONTROL_2_TS_ISET_PREWARM_SUSP          (0b00<<2)
#define REG_NTC_CONTROL_2_TS_ISET_PREWARM_20PCT         (0b01<<2)
#define REG_NTC_CONTROL_2_TS_ISET_PREWARM_40PCT         (0b10<<2)
#define REG_NTC_CONTROL_2_TS_ISET_PREWARM_UNCHANGED     (0b11<<2)
#define REG_NTC_CONTROL_2_TS_VSET_PREWARM_MSK           (0b11<<4)
#define REG_NTC_CONTROL_2_TS_VSET_PREWARM_300MV         (0b00<<4)
#define REG_NTC_CONTROL_2_TS_VSET_PREWARM_200MV         (0b01<<4)
#define REG_NTC_CONTROL_2_TS_VSET_PREWARM_100MV         (0b10<<4)
#define REG_NTC_CONTROL_2_TS_VSET_PREWARM_UNCHANGED     (0b11<<4)
#define REG_NTC_CONTROL_2_TS_VSET_SYM_MSK               (1<<6)
#define REG_NTC_CONTROL_2_TS_VSET_SYM_UNCHANGED         (0<<6)
#define REG_NTC_CONTROL_2_TS_VSET_SYM_MATCHING          (1<<6)
#define REG_CHARGER_STATUS_0_WD_STAT            (1<<0)
#define REG_CHARGER_STATUS_0_SAFETY_TMR_STAT    (1<<1)
#define REG_CHARGER_STATUS_0_VINDPM_STAT        (1<<2)
#define REG_CHARGER_STATUS_0_IINPDM_STAT        (1<<3)
#define REG_CHARGER_STATUS_0_VSYS_STAT          (1<<4)
#define REG_CHARGER_STATUS_0_TREG_STAT          (1<<5)
#define REG_CHARGER_STATUS_0_ADC_DONE_STAT      (1<<6)
#define REG_CHARGER_STATUS_1_VBUS_STAT_MSK          (0x7<<0)
#define REG_CHARGER_STATUS_1_VBUS_STAT(x)           (((x)&0x7)<<0)
#define REG_CHARGER_STATUS_1_CHG_STAT_MSK           (0b11<<3)
#define REG_CHARGER_STATUS_1_CHG_STAT_NOT_CHG       (0b00<<3)
#define REG_CHARGER_STATUS_1_CHG_STAT_CC_CHG        (0b01<<3)
#define REG_CHARGER_STATUS_1_CHG_STAT_CV_CHG        (0b10<<3)
#define REG_CHARGER_STATUS_1_CHG_STAT_TOP_OFF_CHG   (0b11<<3)
#define REG_FAULT_STATUS_0_TS_STAT_MSK          (0x7<<0)
#define REG_FAULT_STATUS_0_TS_STAT_NORMAL       (0x0<<0)
#define REG_FAULT_STATUS_0_TS_STAT_COLD         (0x1<<0)
#define REG_FAULT_STATUS_0_TS_STAT_HOT          (0x2<<0)
#define REG_FAULT_STATUS_0_TS_STAT_COOL         (0x3<<0)
#define REG_FAULT_STATUS_0_TS_STAT_WARM         (0x4<<0)
#define REG_FAULT_STATUS_0_TS_STAT_PRECOOL      (0x5<<0)
#define REG_FAULT_STATUS_0_TS_STAT_PREWARM      (0x6<<0)
#define REG_FAULT_STATUS_0_TS_STAT_BIAS_FAULT   (0x7<<0)
#define REG_FAULT_STATUS_0_SHUT_STAT            (1<<3)
#define REG_FAULT_STATUS_0_SYS_FAULT_STAT       (1<<5)
#define REG_FAULT_STATUS_0_BAT_FAULT_STAT       (1<<6)
#define REG_FAULT_STATUS_0_VBUS_FAULT_STAT      (1<<7)
#define REG_CHARGER_FLAG_0_WD_FLAG              (1<<0)
#define REG_CHARGER_FLAG_0_SAFETY_TMR_FLAG      (1<<1)
#define REG_CHARGER_FLAG_0_VINDPM_FLAG          (1<<2)
#define REG_CHARGER_FLAG_0_IINDPM_FLAG          (1<<3)
#define REG_CHARGER_FLAG_0_VSYS_FLAG            (1<<4)
#define REG_CHARGER_FLAG_0_TREG_FLAG            (1<<5)
#define REG_CHARGER_FLAG_0_ADC_DONE_FLAG        (1<<6)
#define REG_CHARGER_FLAG_1_VBUS_FLAG            (1<<0)
#define REG_CHARGER_FLAG_1_CHG_FLAG             (1<<3)
#define REG_FAULT_FLAG_0_TS_FLAG            (1<<0)
#define REG_FAULT_FLAG_0_TSHUT_FLAG         (1<<3)
#define REG_FAULT_FLAG_0_SYS_FAULT_FLAG     (1<<5)
#define REG_FAULT_FLAG_0_BAT_FAULT_FLAG     (1<<6)
#define REG_FAULT_FLAG_0_VBUS_FAULT_FLAG    (1<<7)
#define REG_CHARGER_MASK_0_WD_MASK              (1<<0)
#define REG_CHARGER_MASK_0_SAFETY_TMR_MASK      (1<<1)
#define REG_CHARGER_MASK_0_VINDPM_MASK          (1<<2)
#define REG_CHARGER_MASK_0_IINDPM_MASK          (1<<3)
#define REG_CHARGER_MASK_0_VSYS_MASK            (1<<4)
#define REG_CHARGER_MASK_0_TREG_MASK            (1<<5)
#define REG_CHARGER_MASK_0_ADC_DONE_MASK        (1<<6)
#define REG_CHARGER_MASK_1_VBUS_MASK            (1<<0)
#define REG_CHARGER_MASK_1_CHG_MASK             (1<<3)
#define REG_FAULT_MASK_0_TS_MASK            (1<<0)
#define REG_FAULT_MASK_0_TSHUT_MASK         (1<<3)
#define REG_FAULT_MASK_0_SYS_FAULT_MASK     (1<<5)
#define REG_FAULT_MASK_0_BAT_FAULT_MASK     (1<<6)
#define REG_FAULT_MASK_0_VBUS_FAULT_MASK    (1<<7)
#define REG_ADC_CONTROL_ADC_AVG_INIT_EXISTING   (0<<2)
#define REG_ADC_CONTROL_ADC_AVG_INIT_NEW        (1<<2)
#define REG_ADC_CONTROL_ADC_AVG_DISABLED        (1<<3)
#define REG_ADC_CONTROL_ADC_AVG_ENABLED         (1<<3)
#define REG_ADC_CONTROL_ADC_SAMPLE_MSK      (0b11<<4)
#define REG_ADC_CONTROL_ADC_SAMPLE_12_BIT   (0b00<<4)
#define REG_ADC_CONTROL_ADC_SAMPLE_11_BIT   (0b01<<4)
#define REG_ADC_CONTROL_ADC_SAMPLE_10_BIT   (0b10<<4)
#define REG_ADC_CONTROL_ADC_SAMPLE_9_BIT    (0b11<<4)
#define REG_ADC_CONTROL_ADC_RATE_MSK        (1<<6)
#define REG_ADC_CONTROL_ADC_RATE_CONTINUOUS (0<<6)
#define REG_ADC_CONTROL_ADC_RATE_ONESHOT    (1<<6)
#define REG_ADC_CONTROL_ADC_EN_MSK          (1<<7)
#define REG_ADC_CONTROL_ADC_EN_DISABLED     (0<<7)
#define REG_ADC_CONTROL_ADC_EN_ENABLED      (1<<7)
#define REG_ADC_FUNCTION_DISABLE_0_VPMID    (1<<0)
#define REG_ADC_FUNCTION_DISABLE_0_TDIE     (1<<1)
#define REG_ADC_FUNCTION_DISABLE_0_TS       (1<<2)
#define REG_ADC_FUNCTION_DISABLE_0_VSYS     (1<<3)
#define REG_ADC_FUNCTION_DISABLE_0_VBAT     (1<<4)
#define REG_ADC_FUNCTION_DISABLE_0_VBUS     (1<<5)
#define REG_ADC_FUNCTION_DISABLE_0_IBAT     (1<<6)
#define REG_ADC_FUNCTION_DISABLE_0_IBUS     (1<<7)
#define REG_IBUS_ADC_VAL(x)             (((x)>>1)&0x7fff)
#define REG_IBAT_ADC_VAL(x)             (((x)>>2)&0x3fff)
#define REG_VBUS_ADC_VAL(x)             (((x)>>2)&0x3fff)
#define REG_VPMID_ADC_VAL(x)            (((x)>>2)&0x1fff)
#define REG_VBAT_ADC_VAL(x)             (((x)>>1)&0x0fff)
#define REG_VSYS_ADC_VAL(x)             (((x)>>1)&0x0fff)
#define REG_TS_ADC_VAL(x)               (((x)>>1)&0x0fff)
#define REG_TDIE_ADC_VAL(x)             (((x)>>1)&0x0fff)
#define REG_PART_INFO_PN_VAL(x)         (((x)>>3)&0x7)
#define REG_PART_INFO_DEV_REV_VAL(x)    (((x)>>0)&0x7)

void pw_battery_init();
void pw_battery_int(uint gp, uint32_t events);

#endif /* BATTERY_PICO_B25628E_H */
